apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: nexgddp
  name: nexgddp
  namespace: prep
spec:
  progressDeadlineSeconds: 2147483647
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      name: nexgddp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: nexgddp
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - apps
      containers:
        - args:
            - start
          env:
            - name: PORT
              value: "3078"
            - name: ENVIRONMENT
              value: staging
            - name: LOCAL_URL
              value: http://nexgddp.prep.svc.cluster.local:3078
            - name: CT_URL
              valueFrom:
                secretKeyRef:
                  key: CT_URL
                  name: mssecrets
            - name: CT_TOKEN
              valueFrom:
                secretKeyRef:
                  key: CT_TOKEN
                  name: mssecrets
            - name: CT_REGISTER_MODE
              valueFrom:
                secretKeyRef:
                  key: CT_REGISTER_MODE
                  name: mssecrets
            - name: API_VERSION
              valueFrom:
                secretKeyRef:
                  key: API_VERSION
                  name: mssecrets
            - name: RASDAMAN_URL
              valueFrom:
                secretKeyRef:
                  key: RASDAMAN_URL
                  name: dbsecrets
            - name: GCLOUD_STORAGE
              valueFrom:
                secretKeyRef:
                  key: GCLOUD_BACKUPS_CREDENTIALS
                  name: mssecrets
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  key: GEE_TILES_REDIS_URI
                  name: dbsecrets
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /opt/nexgddp/storage.json
          image: vizzuality/nexgddp
          imagePullPolicy: Always
          name: nexgddp
          ports:
            - containerPort: 3078
              protocol: TCP
          resources:
            requests:
              cpu: "0"
              memory: "0"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: { }
      terminationGracePeriodSeconds: 30
