dist: bionic
language: python
services:
  - redis
python:
  - "3.6"
addons:
  apt:
    packages:
    - libgdal-dev
install:
    - pip install -r requirements.txt
    - pip install -r requirements_dev.txt
env:
  global:
    - CC_TEST_REPORTER_ID=3058feb388269555b186a45405e669830f9e26a873927f871392dd74e3459192
    - CT_REGISTER_MODE=False
    - PORT=5037
    - API_VERSION=v1
    - LOCAL_URL=http://127.0.0.1:5037
    - CT_URL=http://127.0.0.1:9000
    - CT_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
    - CPLUS_INCLUDE_PATH=/usr/include/gdal
    - C_INCLUDE_PATH=/usr/include/gdal
    - GOOGLE_APPLICATION_CREDENTIALS=./storage.json
    - REDIS_URL=redis://127.0.0.1

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - echo -e "$GCLOUD_STORAGE" | base64 -d > ./storage.json
  - ./cc-test-reporter before-build
script:
  - pytest --cov=nexgddp --cov-report=xml
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
