apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: prep
  labels:
    name: nexgddp
  name: nexgddp
spec:
  revisionHistoryLimit: 0
  template:
    metadata:
      annotations:
        chaos.alpha.kubernetes.io/enabled: "true"
      labels:
        name: nexgddp
    spec:
      containers:
      - name: nexgddp
        image: vizzuality/nexgddp
        imagePullPolicy: Always
        resources:
          requests:
            memory: "0Mi"
            cpu: "0m"
        args:
          - start
        env:
          - name: PORT
            value: "3078"
          - name: ENVIRONMENT
            value: staging
          - name: LOCAL_URL
            value: http://nexgddp.prep.svc.cluster.local:3078
          - name: CT_URL
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_URL
          - name: CT_TOKEN
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_TOKEN
          - name: CT_REGISTER_MODE
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_REGISTER_MODE
          - name: API_VERSION
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: API_VERSION
          - name: RASDAMAN_URL
            valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: RASDAMAN_URL
          - name: GCLOUD_STORAGE
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: GCLOUD_BACKUPS_CREDENTIALS
          - name: REDIS_URL
            valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: GEE_TILES_REDIS_URI
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /opt/nexgddp/storage.json
        ports:
          - containerPort: 3078

      restartPolicy: Always
