apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: prep
  labels:
    name: nexgddp
  name: nexgddp
spec:
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        name: nexgddp
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - apps
      containers:
      - name: nexgddp
        image: vizzuality/nexgddp
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
          limits:
            memory: "512Mi"
        args:
          - start
        env:
          - name: PORT
            value: "3078"
          - name: ENVIRONMENT
            value: prod
          - name: LOCAL_URL
            value: http://nexgddp.prep.svc.cluster.local:3078
          - name: CT_URL
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_URL
          - name: CT_TOKEN
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_TOKEN
          - name: CT_REGISTER_MODE
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_REGISTER_MODE
          - name: API_VERSION
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: API_VERSION
          - name: RASDAMAN_URL
            valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: RASDAMAN_URL
          - name: GCLOUD_STORAGE
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: GCLOUD_BACKUPS_CREDENTIALS
          - name: REDIS_URL
            valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: GEE_TILES_REDIS_URI
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /opt/nexgddp/storage.json
        ports:
          - containerPort: 3078

      restartPolicy: Always
